In [1]:
import pandas as pd

In [2]:
pd.read_json(r'./Dataset/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json("https://api.github.com/users/hadley/orgs")

,login,id,node_id,url,repos_url,events_url,hooks_url,issues_url,members_url,public_members_url,avatar_url,description
0,ggobi,423638,MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==,https://api.github.com/orgs/ggobi,https://api.github.com/orgs/ggobi/repos,https://api.github.com/orgs/ggobi/events,https://api.github.com/orgs/ggobi/hooks,https://api.github.com/orgs/ggobi/issues,https://api.github.com/orgs/ggobi/members{/mem...,https://api.github.com/orgs/ggobi/public_membe...,https://avatars.githubusercontent.com/u/423638...,
1,rstudio,513560,MDEyOk9yZ2FuaXphdGlvbjUxMzU2MA==,https://api.github.com/orgs/rstudio,https://api.github.com/orgs/rstudio/repos,https://api.github.com/orgs/rstudio/events,https://api.github.com/orgs/rstudio/hooks,https://api.github.com/orgs/rstudio/issues,https://api.github.com/orgs/rstudio/members{/m...,https://api.github.com/orgs/rstudio/public_mem...,https://avatars.githubusercontent.com/u/513560...,
2,rstats,722735,MDEyOk9yZ2FuaXphdGlvbjcyMjczNQ==,https://api.github.com/orgs/rstats,https://api.github.com/orgs/rstats/repos,https://api.github.com/orgs/rstats/events,https://api.github.com/orgs/rstats/hooks,https://api.github.com/orgs/rstats/issues,https://api.github.com/orgs/rstats/members{/me...,https://api.github.com/orgs/rstats/public_memb...,https://avatars.githubusercontent.com/u/722735...,None
3,ropensci,1200269,MDEyOk9yZ2FuaXphdGlvbjEyMDAyNjk=,https://api.github.com/orgs/ropensci,https://api.github.com/orgs/ropensci/repos,https://api.github.com/orgs/ropensci/events,https://api.github.com/orgs/ropensci/hooks,https://api.github.com/orgs/ropensci/issues,https://api.github.com/orgs/ropensci/members{/...,https://api.github.com/orgs/ropensci/public_me...,https://avatars.githubusercontent.com/u/120026...,Tools and R Packages for Open Science
4,rjournal,3330561,MDEyOk9yZ2FuaXphdGlvbjMzMzA1NjE=,https://api.github.com/orgs/rjournal,https://api.github.com/orgs/rjournal/repos,https://api.github.com/orgs/rjournal/events,https://api.github.com/orgs/rjournal/hooks,https://api.github.com/orgs/rjournal/issues,https://api.github.com/orgs/rjournal/members{/...,https://api.github.com/orgs/rjournal/public_me...,https://avatars.githubusercontent.com/u/333056...,None
5,r-dbi,5695665,MDEyOk9yZ2FuaXphdGlvbjU2OTU2NjU=,https://api.github.com/orgs/r-dbi,https://api.github.com/orgs/r-dbi/repos,https://api.github.com/orgs/r-dbi/events,https://api.github.com/orgs/r-dbi/hooks,https://api.github.com/orgs/r-dbi/issues,https://api.github.com/orgs/r-dbi/members{/mem...,https://api.github.com/orgs/r-dbi/public_membe...,https://avatars.githubusercontent.com/u/569566...,R + databases
6,RConsortium,15366137,MDEyOk9yZ2FuaXphdGlvbjE1MzY2MTM3,https://api.github.com/orgs/RConsortium,https://api.github.com/orgs/RConsortium/repos,https://api.github.com/orgs/RConsortium/events,https://api.github.com/orgs/RConsortium/hooks,https://api.github.com/orgs/RConsortium/issues,https://api.github.com/orgs/RConsortium/member...,https://api.github.com/orgs/RConsortium/public...,https://avatars.githubusercontent.com/u/153661...,"The R Consortium, Inc was established to provi..."
7,tidyverse,22032646,MDEyOk9yZ2FuaXphdGlvbjIyMDMyNjQ2,https://api.github.com/orgs/tidyverse,https://api.github.com/orgs/tidyverse/repos,https://api.github.com/orgs/tidyverse/events,https://api.github.com/orgs/tidyverse/hooks,https://api.github.com/orgs/tidyverse/issues,https://api.github.com/orgs/tidyverse/members{...,https://api.github.com/orgs/tidyverse/public_m...,https://avatars.githubusercontent.com/u/220326...,The tidyverse is a collection of R packages th...
8,r-lib,22618716,MDEyOk9yZ2FuaXphdGlvbjIyNjE4NzE2,https://api.github.com/orgs/r-lib,https://api.github.com/orgs/r-lib/repos,https://api.github.com/orgs/r-lib/events,https://api.github.com/orgs/r-lib/hooks,https://api.github.com/orgs/r-lib/issues,https://api.github.com/orgs/r-lib/members{/mem...,https://api.github.com/orgs/r-lib/public_membe...,https://avatars.githubusercontent.com/u/226187...,
9,rstudio-education,34165516,MDEyOk9yZ2FuaXphdGlvbjM0MTY1NTE2,https://api.github.com/orgs/rstudio-education,https://api.github.com/orgs/rstudio-education/...,https://api.github.com/orgs/rstudio-education/...,https://api.github.com/orgs/rstudio-education/...,https://api.github.com/orgs/rstudio-education/...,https://api.github.com/orgs/rstudio-education/...,https://api.github.com/orgs/rstudio-education/...,https://avatars.githubusercontent.com/u/341655...,

In [4]:
# SQL
import mysql.connector

In [6]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="world"
)

In [23]:
pd.read_sql_query(
    """
    SELECT * 
    FROM city 
    WHERE CountryCode = 'USA'
    and Population > 1000000
    """, conn)

C:\Users\Rakib\AppData\Local\Temp\ipykernel_25168\971253081.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

     ID          Name CountryCode      District  Population
0  3793      New York         USA      New York     8008278
1  3794   Los Angeles         USA    California     3694820
2  3795       Chicago         USA      Illinois     2896016
3  3796       Houston         USA         Texas     1953631
4  3797  Philadelphia         USA  Pennsylvania     1517550
5  3798       Phoenix         USA       Arizona     1321045
6  3799     San Diego         USA    California     1223400
7  3800        Dallas         USA         Texas     1188580
8  3801   San Antonio         USA         Texas     1144646